name: Secure CI/CD Pipeline

on:
  push:
  pull_request:

# Required for uploading to the Security tab
permissions:
  contents: read
  security-events: write

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ---------------------------
      # Run Gitleaks
      # ---------------------------
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xvzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: |
          gitleaks detect --report-format sarif --report-path gitleaks.sarif --exit-code 0

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif


      # ---------------------------
      # Run pip-audit
      # ---------------------------
      - name: Install pip-audit (latest)
        run: pip install --upgrade pip-audit

      - name: Run pip-audit with SARIF
        run: |
          pip-audit -r requirements.txt -f sarif -o pip-audit.sarif || true

      - name: Upload pip-audit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif



      # ---------------------------
      # Run Bandit
      # ---------------------------
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f sarif -o bandit.sarif || true

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      # ---------------------------
      # Run Trivy
      # ---------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

      - name: Build Docker image
        run: docker build -t insecure-app .

      - name: Run Trivy on Docker image
        run: |
          trivy image --format sarif --output trivy-image.sarif insecure-app || true

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
