name: CI - Security Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Static App Analysis (Bandit) ---
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit (fail on findings)
        run: |
          bandit -r . -f json -o bandit-report.json
      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      # --- Dependency Vulnerability Scan (pip-audit) ---
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit (strict)
        run: |
          pip-audit -r requirements.txt --format json --output pip-audit.json --strict
      - name: Upload pip-audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: pip-audit.json

      # --- Secrets Scanning (Gitleaks) ---
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks.sarif
      - name: Upload Gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.sarif

      # --- Build Docker image (uses the active Dockerfile) ---
      - name: Build Docker image
        run: |
          docker build -t app:ci .

      # --- Trivy filesystem scan (repo) ---
      - name: Trivy FS scan (HIGH/CRITICAL -> fail)
        run: |
          docker run --rm -v "$PWD":/src aquasec/trivy:latest fs --no-progress --severity HIGH,CRITICAL --exit-code 1 /src
      - name: Upload Trivy FS result (SARIF)
        if: always()
        run: |
          docker run --rm -v "$PWD":/src -w /src aquasec/trivy:latest fs --no-progress --format sarif --output trivy-fs.sarif /src
      - name: Upload Trivy FS artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs.sarif

      # --- Trivy image scan ---
      - name: Trivy Image scan (HIGH/CRITICAL -> fail)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --no-progress --severity HIGH,CRITICAL --exit-code 1 app:ci
      - name: Upload Trivy Image result (SARIF)
        if: always()
        run: |
          docker save app:ci -o image.tar
          docker run --rm -v "$PWD":/src -w /src aquasec/trivy:latest image --input image.tar --no-progress --format sarif --output trivy-image.sarif
      - name: Upload Trivy Image artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image.sarif
